---
#-------------------------------
# General Site Settings
title: Luísa Moura
logo: logo.png
description: Just trying random stuff

#-------------------------------
# Author Settings
author:
  name: Luísa Moura
  image: luisa_moura.png
  say-hello: Hey, I’m <strong>Luísa Moura</strong> 🖖
  bio: Software Engineer at <strong>Cohere</strong> and Computer Scientist (<strong>University of São Paulo</strong>). Here you'll find some of my personal and professional projetcts (probably some random stuff as well).

#-------------------------------
# Contact links
linkedin: https://linkedin.com/in/luisamoura
github: https://github.com/lusmoura
instagram: https://instagram.com/luisamoura.py # Add your Instagram handle

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: lusmoura # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: luisamoura.py # Add instagram username

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
